import os
os.makedirs("dashboard", exist_ok=True)

lines = []
lines.append("import streamlit as st")
lines.append("import pandas as pd")
lines.append("import plotly.express as px")
lines.append("import plotly.graph_objects as go")
lines.append("from sqlalchemy import create_engine")
lines.append("import os")
lines.append("")
lines.append("st.set_page_config(page_title='E-Commerce Intelligence Dashboard', page_icon='📊', layout='wide')")
lines.append("")
lines.append("DB_URI = 'postgresql://ecommerce_user:ecommerce_pass@localhost:5432/ecommerce_db'")
lines.append("")
lines.append("@st.cache_resource")
lines.append("def get_engine():")
lines.append("    return create_engine(DB_URI)")
lines.append("")
lines.append("@st.cache_data")
lines.append("def load_table(table_name):")
lines.append("    engine = get_engine()")
lines.append("    return pd.read_sql(f'SELECT * FROM {table_name}', engine)")
lines.append("")
lines.append("CHARTS = 'charts'")
lines.append("")
lines.append("def show_html_chart(filename, height=500):")
lines.append("    path = os.path.join(CHARTS, filename)")
lines.append("    if os.path.exists(path):")
lines.append("        with open(path, 'r') as f:")
lines.append("            html = f.read()")
lines.append("        st.components.v1.html(html, height=height, scrolling=True)")
lines.append("    else:")
lines.append("        st.warning(f'Chart not found: {filename}')")
lines.append("")
lines.append("def show_png_chart(filename):")
lines.append("    path = os.path.join(CHARTS, filename)")
lines.append("    if os.path.exists(path):")
lines.append("        st.image(path, use_column_width=True)")
lines.append("    else:")
lines.append("        st.warning(f'Chart not found: {filename}')")
lines.append("")
lines.append("st.sidebar.title('📊 E-Commerce Dashboard')")
lines.append("st.sidebar.markdown('**NCI MSc Data Analytics**')")
lines.append("st.sidebar.markdown('Semester 2, 2025/26')")
lines.append("st.sidebar.markdown('---')")
lines.append("page = st.sidebar.radio('Navigate to', ['🏠 Overview', '📦 Amazon — Consumer Purchases', '🛒 UCI — Shopper Behaviour', '📢 Criteo — Campaign Attribution', '🔗 Cross-Dataset Intelligence'])")
lines.append("st.sidebar.markdown('---')")
lines.append("st.sidebar.markdown('**Team**')")
lines.append("st.sidebar.markdown('- Amber (M3 — Criteo)')")
lines.append("st.sidebar.markdown('- Ibrahim (M1 — Amazon)')")
lines.append("st.sidebar.markdown('- Araf (M2 — UCI)')")
lines.append("")
lines.append("if page == '🏠 Overview':")
lines.append("    st.title('E-Commerce Customer Behaviour & Sales Intelligence Dashboard')")
lines.append("    st.markdown('### Multi-Dataset Exploration: Consumer Purchases, Shopper Conversion, and Campaign Attribution')")
lines.append("    st.markdown('---')")
lines.append("    col1, col2, col3 = st.columns(3)")
lines.append("    try:")
lines.append("        df_amazon = load_table('amazon_clean')")
lines.append("        col1.metric('Amazon Records', f'{len(df_amazon):,}')")
lines.append("        col1.metric('Amazon Categories', f\"{df_amazon['category'].nunique():,}\")")
lines.append("    except:")
lines.append("        col1.metric('Amazon Records', 'Load DB')")
lines.append("    try:")
lines.append("        df_uci = load_table('uci_clean')")
lines.append("        col2.metric('UCI Sessions', f'{len(df_uci):,}')")
lines.append("        col2.metric('Conversion Rate', f\"{df_uci['is_conversion'].mean()*100:.1f}%\")")
lines.append("    except:")
lines.append("        col2.metric('UCI Sessions', 'Load DB')")
lines.append("    try:")
lines.append("        df_criteo = load_table('criteo_clean')")
lines.append("        col3.metric('Criteo Impressions', f'{len(df_criteo):,}')")
lines.append("        col3.metric('Campaigns', f\"{df_criteo['campaign'].nunique():,}\")")
lines.append("    except:")
lines.append("        col3.metric('Criteo Impressions', 'Load DB')")
lines.append("    st.markdown('---')")
lines.append("    st.markdown('### Research Questions')")
lines.append("    col1, col2 = st.columns(2)")
lines.append("    with col1:")
lines.append("        st.info('RQ1 — Consumer Purchase Trends: How have spending patterns evolved over time?')")
lines.append("        st.info('RQ2 — Shopper Behaviour: What on-site signals predict purchase conversion?')")
lines.append("    with col2:")
lines.append("        st.info('RQ3 — Campaign Attribution: Which campaigns deliver highest ROI?')")
lines.append("        st.info('RQ4 — Cross-Dataset Intelligence: Can we align RFM, intent signals, and campaign touchpoints?')")
lines.append("")
lines.append("elif page == '📦 Amazon — Consumer Purchases':")
lines.append("    st.title('📦 Amazon Consumer Purchase Analysis')")
lines.append("    st.markdown('**Member 1 — Ibrahim | Amazon US Purchase History**')")
lines.append("    st.markdown('---')")
lines.append("    tab1, tab2, tab3 = st.tabs(['Revenue and Trends', 'Categories and Geography', 'RFM Segmentation'])")
lines.append("    with tab1:")
lines.append("        st.subheader('Monthly Revenue Trend')")
lines.append("        show_html_chart('m1_revenue_trend.html')")
lines.append("        st.subheader('Revenue by Day of Week')")
lines.append("        show_html_chart('m1_dow_revenue.html')")
lines.append("    with tab2:")
lines.append("        st.subheader('Top 10 Categories by Revenue')")
lines.append("        show_html_chart('m1_top_categories.html')")
lines.append("        st.subheader('Revenue by US State')")
lines.append("        show_html_chart('m1_state_revenue.html')")
lines.append("        st.subheader('Price Band Distribution')")
lines.append("        show_html_chart('m1_price_band.html')")
lines.append("    with tab3:")
lines.append("        st.subheader('RFM Customer Segmentation')")
lines.append("        show_html_chart('m1_rfm_scatter.html')")
lines.append("        try:")
lines.append("            rfm = load_table('amazon_rfm')")
lines.append("            seg_counts = rfm['segment'].value_counts().reset_index()")
lines.append("            seg_counts.columns = ['segment', 'count']")
lines.append("            fig = px.pie(seg_counts, names='segment', values='count', title='RFM Segment Distribution')")
lines.append("            st.plotly_chart(fig, use_container_width=True)")
lines.append("        except Exception as e:")
lines.append("            st.error(f'Could not load RFM data: {e}')")
lines.append("")
lines.append("elif page == '🛒 UCI — Shopper Behaviour':")
lines.append("    st.title('🛒 UCI Online Shopper Behaviour Analysis')")
lines.append("    st.markdown('**Member 2 — Araf | UCI Online Shoppers Intention**')")
lines.append("    st.markdown('---')")
lines.append("    tab1, tab2, tab3 = st.tabs(['Conversion Analysis', 'Traffic and Visitors', 'Session Quality'])")
lines.append("    with tab1:")
lines.append("        st.subheader('Purchase Conversion Funnel')")
lines.append("        show_html_chart('m2_conversion_funnel.html')")
lines.append("        st.subheader('Weekend vs Weekday Conversion')")
lines.append("        show_html_chart('m2_weekend_weekday.html')")
lines.append("        st.subheader('Page Values by Conversion Outcome')")
lines.append("        show_html_chart('m2_page_values_conversion.html')")
lines.append("    with tab2:")
lines.append("        st.subheader('Conversion Rate by Traffic Source')")
lines.append("        show_html_chart('m2_traffic_source.html')")
lines.append("        st.subheader('New vs Returning Visitor Analysis')")
lines.append("        show_html_chart('m2_visitor_type.html')")
lines.append("    with tab3:")
lines.append("        st.subheader('Bounce Rate Heatmap')")
lines.append("        show_png_chart('m2_bounce_heatmap.png')")
lines.append("        st.subheader('Session Quality by Visitor Type')")
lines.append("        show_html_chart('m2_session_quality.html')")
lines.append("")
lines.append("elif page == '📢 Criteo — Campaign Attribution':")
lines.append("    st.title('📢 Criteo Digital Campaign Attribution Analysis')")
lines.append("    st.markdown('**Member 3 — Amber | Criteo Attribution Dataset**')")
lines.append("    st.markdown('---')")
lines.append("    tab1, tab2, tab3 = st.tabs(['Campaign Performance', 'Cost and ROAS', 'Attribution and Timing'])")
lines.append("    with tab1:")
lines.append("        st.subheader('Top 20 Campaigns by Conversion Rate')")
lines.append("        show_html_chart('m3_campaign_conversion_rate.html')")
lines.append("        st.subheader('Conversions by Attribution Model')")
lines.append("        show_html_chart('m3_attribution_waterfall.html')")
lines.append("    with tab2:")
lines.append("        st.subheader('Top 20 Most Efficient Campaigns by CPO')")
lines.append("        show_html_chart('m3_cpo_by_campaign.html')")
lines.append("        st.subheader('ROAS vs Average Cost by Campaign')")
lines.append("        show_html_chart('m3_roas_scatter.html')")
lines.append("    with tab3:")
lines.append("        st.subheader('Conversion Rate by Click Recency')")
lines.append("        show_html_chart('m3_click_recency_conversion.html')")
lines.append("        st.subheader('Conversion Rate by Hour of Day')")
lines.append("        show_html_chart('m3_hourly_conversion.html')")
lines.append("        st.subheader('Conversion Rate by Day of Week')")
lines.append("        show_html_chart('m3_dow_conversion.html')")
lines.append("")
lines.append("elif page == '🔗 Cross-Dataset Intelligence':")
lines.append("    st.title('🔗 Cross-Dataset Intelligence')")
lines.append("    st.markdown('**Unified view combining insights from all three datasets**')")
lines.append("    st.markdown('---')")
lines.append("    st.subheader('Amazon Price Bands + Criteo Campaign Efficiency')")
lines.append("    st.markdown('Amber — combines Amazon spending patterns with Criteo campaign cost efficiency')")
lines.append("    show_png_chart('cross_amber_amazon_criteo.png')")
lines.append("    st.markdown('---')")
lines.append("    st.subheader('Amazon Quarterly Revenue + Criteo Attribution Performance')")
lines.append("    st.markdown('Ibrahim — Amazon seasonal revenue vs Criteo attribution model comparison')")
lines.append("    show_png_chart('cross_ibrahim_amazon_criteo_quarterly.png')")
lines.append("    st.markdown('---')")
lines.append("    st.subheader('Amazon Hourly Orders + Criteo Hourly Conversion')")
lines.append("    st.markdown('Ibrahim — are ad campaigns running at peak purchase hours')")
lines.append("    show_png_chart('cross_ibrahim_amazon_criteo_hourly.png')")
lines.append("    st.markdown('---')")
lines.append("    st.subheader('Amazon RFM Segments + UCI Session Quality')")
lines.append("    st.markdown('Araf — maps Amazon customer value tiers against UCI shopper session behaviour')")
lines.append("    show_png_chart('cross_araf_rfm_vs_uci_sessions.png')")

with open("dashboard/app.py", "w") as f:
    f.write("\n".join(lines))

print("dashboard/app.py created successfully")
print("Lines:", len(lines))
